#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
# Displays username
# Displays user id 
# Displays Home directory path for the user

line=/etc/passwd
while IFS=: read -r | cut -d: -f1,3,6 /etc/passwd; 
do
echo "$line: $PATH" 
done
