#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
# Displays username
# Displays user id 
# Displays Home directory path for the user

line=/etc/passwd
while read -r line; do echo \"$line\" | cut -d: -f1,3,6; done < /etc/passwd
